### ISSUE TITLE
the abnomal distribution of the gaspy elements, how could deal with it 

### ISSUE THREAD

**Issue by Jiangjiangzhang6** [Immortal2333/Telemeres_and_Centromeres#1]
hello
I use your method to identified the centromeres. but the igv is like this.
![e3bd77b7af9eda23980b305c4c7dc97](https://github.com/Immortal2333/Telomeres_and_Centromeres/assets/101324838/79b83a6c-8bf9-45cf-a708-2d12f4348d7f)
and the gaspy elements was abnormal, so I want to ask how could it emrge this error? 
And my genome was gap-free, assemblied main frame use th hifi data  and gap-filling use the graph assemblied by clr data.
the genome busco and protein busco were 99.8% and 96%, respectively. the LAI was 23, so I think the genome quality should be good. 
so this case was abnoml or not , how could i deal with it.
thank you

**Comment by Immortal2333** [comment]
It is a common phenomenon in most plants to identify the centromere region. To accomplish this, you can zoom in on the peak of the chromosome and combine it with TRF repeat units, utilizing IGV visualization. If you'd like, you can send the 'genome_trf.split.gff' file to my email at [571720850@qq.com](mailto:571720850@qq.com). I will do my best to assist you in finding the TRF repeat units, provided I am available. Good luck with your endeavors!
