### ISSUE TITLE
questions about "genome.gff" file

### ISSUE THREAD

**Issue by MuyuenLP** [Immortal2333/Telemeres_and_Centromeres#3]
Dear Immortal2333,
So ashamed to raise an issue again.
I want to know about how to get the "genome.gff" file ,is it the gene annotation file?
Best wishes

**Comment by Immortal2333** [comment]
Yes, it is. You can find them through these channels.

**Data availability**
All PacBio sequence data have been deposited in the NCBI Sequence Read Archive under project number `PRJNA882193` and
the National Genomics Data Center (NGDC) Genome Sequence Archive (GSA) (`https://ngdc.cncb.ac.cn/gsa/`), with BioProject
number `PRJCA012093`. The assembly and annotation as well as the sequences of centromeres and heterozygous regions have
been deposited in zenodo: `https://zenodo.org/record/7751391#.ZBgVmcJBy3A`. The assembly and its annotation will be also
hosted in the GRAPEDIA portal (`https://grapedia.org/`).

**Comment by MuyuenLP** [comment]
> Yes, it is. You can find them through these channels.
> 
> **Data availability** All PacBio sequence data have been deposited in the NCBI Sequence Read Archive under project number `PRJNA882193` and the National Genomics Data Center (NGDC) Genome Sequence Archive (GSA) (`https://ngdc.cncb.ac.cn/gsa/`), with BioProject number `PRJCA012093`. The assembly and annotation as well as the sequences of centromeres and heterozygous regions have been deposited in zenodo: `https://zenodo.org/record/7751391#.ZBgVmcJBy3A`. The assembly and its annotation will be also hosted in the GRAPEDIA portal (`https://grapedia.org/`).

Thank you.I download the file and put it into IGV,but it seems a little different from your plot in paper,so i raised this issue.Maybe it's because of the different resolutions.
