### ISSUE TITLE
The meaning of Fig. 3C in the paper

### ISSUE THREAD

**Issue by MuyuenLP** [Immortal2333/Telemeres_and_Centromeres#5]
Dear Immortal2333,
I'm really sorry I keep raising issues, but it should be over soon.
Could you please provide some details about this Fig,like what does it mean, what data is used to draw it, etc.
![image](https://github.com/Immortal2333/Telomeres_and_Centromeres/assets/126345154/d424a8ba-3497-43b4-8847-4dcff81080de)
Best wishes

**Comment by MuyuenLP** [comment]
So it is the clustering of the centromere sequence?Can the centromere sequence file be obtained through this pipeline?

**Comment by Immortal2333** [comment]
So sorry to reply late.

This is the clustering of the centromere sequence. The `cons_seq=XXX` sequence of the longest 107-bp is extracted from each chromosome in the `genome_trf.split.txt` file. You can sort it in ascending order based on the number of copies of `period=107`. After reverse complementarity of the repeat unit of consensus sequence (if necessary) and setting a starting position, you can align and visualize it using DNAman or GeneDoc software. Just like the figure depicted in this paper.

Best regards

**Comment by MuyuenLP** [comment]
Dear Immortal2333,

Thank you very much for your timely and useful reply. I am an undergraduate student majoring in computer science and have almost no biological foundation. With your help, I have completed the entire pipeline. Thank you again.I wish you all the best in your research endeavors

Best regards
